### ISSUE TITLE
re-write setAshParam

### ISSUE THREAD

**Issue by heejungshim** [stephenslab/multiseq#2]
setAshParam function would be better written using modifyList?

**Comment by stephens999** [comment]
i've modfied ash's input flags. we'll have to update multiseq. Here's what i think the setAshParam function should look like, but I don't think i have a good way to test it 

setAshParam <- function(ashparam){
  if (!is.list(ashparam))
    stop("Error: invalid parameter 'ashparam'")
  if (!is.null(ashparam[["g"]]))
    stop(
      "Error: ash parameter 'g' can only be NULL; if you want to specify ash parameter 'g' use multiseq arguments 'fitted.g' and/or 'fitted.g.intercept'"
    )
  if (!((is.null(ashparam[["mixsd"]])) |
        (is.numeric(ashparam[["mixsd"]]) &
         (length(ashparam[["mixsd"]]) < 2))))
    stop("Error: invalid parameter 'mixsd', 'mixsd'  must be null or a numeric vector of length >=2")
  if (!((ashparam[["prior"]] == "nullbiased") |
        (ashparam[["prior"]] == "uniform") |
        is.numeric(ashparam[["prior"]])))
    stop("Error: invalid parameter 'prior', 'prior' can be a number or 'nullbiased' or 'uniform'")
  default = list(
    g = NULL,mixsd = NULL,df = NULL,pointmass = TRUE,prior = "nullbiased",
    gridmult = 2,control = list(maxiter = 5000,trace = FALSE),mixcompdist =
      "normal",randomstart = FALSE,outputlevel=1
  )
  
  ashparam = modifyList(default,ashparam)
  return(ashparam)
}

**Comment by stephens999** [comment]
fixed.
